name: Lint Python Code

on: 
  workflow_dispatch:
  #push:

jobs:
  run_python_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: cd app && pip install -r requirements.txt

      - name: Install linter (PyLint)
        run: pip install pylint

      - name: Lint Python code
        run: cd app && pylint *.py
